#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Geoff Seemueller
# This file is part of muxox, released under the MIT License.
#
# Flattens the muxox workspace (muxox-core + muxox-web + tui-bridge + the muxox
# binary) into a single publishable crate under publish/muxox.
#
# The workspace crates keep their `muxox_core::` / `muxox_web::` / `tui_bridge::`
# import paths verbatim: the staged lib.rs aliases them back onto itself with
# `extern crate self as ...`, and every module is copied flat into src/ so the
# `crate::` and `super::` paths they already use still resolve.
#
# Nothing here enumerates individual modules -- sources are globbed and the
# module declarations are lifted from each crate's own lib.rs -- so adding a
# module to a workspace crate flows through without touching this script.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STAGE="$ROOT/publish/muxox"

meta() { awk -F '"' -v k="$1" '$0 ~ "^"k" = " { print $2; exit }' "$2"; }
meta_raw() { awk -v k="$1" '$0 ~ "^"k" = " { sub("^"k" = ", ""); print; exit }' "$2"; }

VERSION="$(meta version "$ROOT/Cargo.toml")"
EDITION="$(meta edition "$ROOT/Cargo.toml")"
LICENSE="$(meta license "$ROOT/Cargo.toml")"
REPOSITORY="$(meta repository "$ROOT/Cargo.toml")"
HOMEPAGE="$(meta homepage "$ROOT/Cargo.toml")"
AUTHORS="$(meta_raw authors "$ROOT/Cargo.toml")"

BIN_MANIFEST="$ROOT/crates/muxox/Cargo.toml"
DESCRIPTION="$(meta description "$BIN_MANIFEST")"
DOCUMENTATION="$(meta documentation "$BIN_MANIFEST")"
KEYWORDS="$(meta_raw keywords "$BIN_MANIFEST")"
CATEGORIES="$(meta_raw categories "$BIN_MANIFEST")"

# Lifted verbatim rather than duplicated: the staged crate is its own workspace
# root, so it has to carry its own copy of the release profile.
RELEASE_PROFILE="$(awk '
  /^\[/ { inblock = ($0 == "[profile.release]") }
  inblock { print }
' "$ROOT/Cargo.toml")"

for var in VERSION EDITION LICENSE REPOSITORY HOMEPAGE AUTHORS DESCRIPTION DOCUMENTATION KEYWORDS CATEGORIES RELEASE_PROFILE; do
  if [[ -z "${!var}" ]]; then
    echo "failed to read $var from workspace metadata" >&2
    exit 1
  fi
done

# --- clean the stage, but never clobber something we did not generate ---
if [[ -d "$STAGE" ]]; then
  if [[ -f "$STAGE/.muxox-generated" ]] ||
     [[ -z "$(find "$STAGE" -mindepth 1 ! -path "$STAGE/target" ! -path "$STAGE/target/*" -type f -print -quit)" ]]; then
    rm -rf "$STAGE"
  else
    echo "$STAGE exists and was not generated by this script; refusing to overwrite it" >&2
    exit 1
  fi
fi

mkdir -p "$STAGE/src" "$STAGE/tests"
printf 'generated by scripts/stage-crates-io.sh\n' > "$STAGE/.muxox-generated"

cp "$ROOT/README.md" "$STAGE/README.md"
cp "$ROOT/LICENSE" "$STAGE/LICENSE"
cp "$ROOT/muxox.example.toml" "$STAGE/muxox.example.toml"
[[ -f "$ROOT/Cargo.lock" ]] && cp "$ROOT/Cargo.lock" "$STAGE/Cargo.lock"

# Copy one crate's src/ into the flat stage root. lib.rs and main.rs are the
# crate's own wiring and are regenerated below; everything else (modules,
# submodule directories, include_str! assets) moves across as-is. Any name
# collision between crates is a hard error rather than a silent overwrite.
stage_src() {
  local src="$ROOT/crates/$1/src"
  local entry dest
  for entry in "$src"/*; do
    [[ -e "$entry" ]] || continue
    dest="$STAGE/src/$(basename "$entry")"
    case "$(basename "$entry")" in
      lib.rs | main.rs) continue ;;
    esac
    if [[ -e "$dest" ]]; then
      echo "collision staging $1: src/$(basename "$entry") already exists" >&2
      exit 1
    fi
    cp -R "$entry" "$dest"
  done
}

stage_src muxox-core
stage_src muxox-web
stage_src tui-bridge
stage_src muxox

# The binary's main.rs becomes `cli.rs` inside the lib (so it can keep using
# `muxox_core::` via the self-alias); main.rs is regenerated as a shim below.
perl -0pe '
  s/^mod modes;\n\n?//m;
  s/^use modes::/use crate::modes::/m;
  s/^async fn main\(\)/pub async fn run()/m;
' "$ROOT/crates/muxox/src/main.rs" > "$STAGE/src/cli.rs"

if ! grep -q '^pub async fn run()' "$STAGE/src/cli.rs"; then
  echo "failed to rewrite crates/muxox/src/main.rs into src/cli.rs" >&2
  exit 1
fi

# Integration tests reach in through the published crate name.
for t in "$ROOT"/crates/muxox/tests/*.rs; do
  perl -0pe 's/\b(?:muxox_core|muxox_web|tui_bridge)::/muxox::/g' \
    "$t" > "$STAGE/tests/$(basename "$t")"
done

# --- lib.rs: self-aliases, then each crate's own module list verbatim ---
cat > "$STAGE/src/lib.rs" <<'EOF'
// SPDX-License-Identifier: MIT
// Copyright (c) 2025 Geoff Seemueller
// This file is part of muxox, released under the MIT License.
//
// Generated by scripts/stage-crates-io.sh -- do not edit by hand.
//
// muxox is developed as a workspace (muxox-core, muxox-web, tui-bridge, muxox)
// and published as a single crate. These aliases let the merged sources keep
// their original cross-crate import paths.

extern crate self as muxox_core;
extern crate self as muxox_web;
extern crate self as tui_bridge;

EOF

emit_mods() {
  printf '// --- %s ---\n' "$1" >> "$STAGE/src/lib.rs"
  cat "$ROOT/crates/$1/src/lib.rs" >> "$STAGE/src/lib.rs"
  printf '\n' >> "$STAGE/src/lib.rs"
}

emit_mods muxox-core
emit_mods muxox-web
emit_mods tui-bridge

cat >> "$STAGE/src/lib.rs" <<'EOF'
// --- muxox (binary) ---
pub mod cli;
pub mod modes;
EOF

cat > "$STAGE/src/main.rs" <<'EOF'
// SPDX-License-Identifier: MIT
// Copyright (c) 2025 Geoff Seemueller
// This file is part of muxox, released under the MIT License.
//
// Generated by scripts/stage-crates-io.sh -- do not edit by hand.

fn main() -> anyhow::Result<()> {
    muxox::cli::run()
}
EOF

cat > "$STAGE/Cargo.toml" <<EOF
# Generated by scripts/stage-crates-io.sh -- do not edit by hand.
[package]
name = "muxox"
version = "$VERSION"
edition = "$EDITION"
authors = $AUTHORS
description = "$DESCRIPTION"
license = "$LICENSE"
repository = "$REPOSITORY"
homepage = "$HOMEPAGE"
documentation = "$DOCUMENTATION"
readme = "README.md"
keywords = $KEYWORDS
categories = $CATEGORIES
exclude = ["target/", ".muxox-generated"]

[lib]
name = "muxox"
path = "src/lib.rs"

[[bin]]
name = "muxox"
path = "src/main.rs"

# Union of the workspace crates' dependencies. Keep in sync with
# crates/*/Cargo.toml when adding or bumping a dependency.
[dependencies]
anyhow = "1"
axum = { version = "0.7", features = ["ws"] }
clap = { version = "4", features = ["derive"] }
crossterm = "0.28"
dioxus = { version = "0.7", features = ["fullstack", "ssr"] }
dioxus-core = "0.7"
directories = "5"
futures-util = "0.3"
open = "5"
ratatui = "0.28"
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
toml = "0.8"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.28", features = ["signal", "process", "sched"] }

[target.'cfg(unix)'.dev-dependencies]
nix = { version = "0.28", features = ["signal", "process"] }

# The published crate is its own workspace root, so it does not inherit the
# workspace [profile.release]. It is lifted verbatim from the root Cargo.toml
# below, so \`cargo install muxox\` produces the same binary as our releases.
$RELEASE_PROFILE

[workspace]
EOF

echo "Staged crates.io package at $STAGE"
echo "Verify:  cargo test    --manifest-path publish/muxox/Cargo.toml"
echo "Package: cargo package --manifest-path publish/muxox/Cargo.toml"
echo "Publish: cargo publish --manifest-path publish/muxox/Cargo.toml"
